//
// Copyright (c) 2017 Contributors to the Eclipse Foundation
//
// See the NOTICE file(s) distributed with this work for additional
// information regarding copyright ownership.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

:sectanchors:
:doctype: book
:license: Apache License v2.0
:source-highlighter: coderay
:sectnums:
:toc: left
:toclevels: 4

= MicroProfile OpenAPI Specification

== Introduction

== Architecture

== OpenAPI Endpoint

=== Overview
A fully processed and valid OpenAPI document must be available at the root
URL `/openapi`, as a `HTTP GET` operation.

For example, `GET http://myHost:myPort/openapi`.

This document represents the result of the applied <<Processing rules>>.

=== Content format
The default `Content-Type` of the `/openapi` endpoint is `application/yaml`.

Vendors must also support the type `application/json` if requested via the
`Accept` header.

=== Query parameters
No query parameter are required for the `/openapi` endpoint.  However, one
suggested but optional query parameter for vendors to support is `format`,
where the value can be `json`, to facilate the toggle between the default `yaml`
format and `json` format.

=== Context root behaviour
Vendors are required to ensure that the combination of each global https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#serverObject[server]
element and https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#pathItemObject[pathItem] element resolve to the absolute backend URL of that
particular path.  If that `pathItem` contains a `servers` element , then this
list of operation-level `server` elements replaces the global list of servers
for that particular `pathItem`.

For example:  an application may have an `ApplicationPath` annotation with the
value of `/`, but is assigned the context root of `/myApp` during deployment. In
this case, the `server` elements (either global or operation-level) must either
end with `/myApp` or a corresponding proxy.  Alternatively it is valid, but discourauged, to
add that context root (`/myApp`) to every `pathItem` defined in that application.

=== Multiple applications

The 1.0 version of the MicroProfile OpenAPI specification does not define how
the `/openapi` endpoint may be partitioned in the event that the MicroProfile
runtime supports deployment of multiple applications. If an implementation wishes
to support multiple applications within a MicroProfile runtime, the semantics of
the `/openapi` endpoint are expected to be the logical AND of all the application
in the runtime, which would imply merging multiple OpenAPI documents into a single
valid document (handling conflicting IDs and unique names).

== Configuration
=== List of configurable items
=== Configuration approaches
=== Vendor specific configuration

== Documentation Mechanisms

=== Annotations

==== Table of annotations
==== Usage

===== Operation
===== ApiResponse
===== Servers
===== Schema
===== And more.....

=== Models
==== How to build OpenAPI model in Java™

=== Filter/Interceptor
==== Filter mechanics

=== Static OpenAPI files
==== Location and formats
==== Precedence

=== Processing rules

The processed document available from `/openapi` is built from a variety of sources,
which were outlined in the sub-headings of <<Documentation Mechanisms>>.  Vendors
are required to process these different sources in the following order:

1. Configuration values from `mp.openapi` namespace
2. OASModelReader
3. OASFilter
4. Static OpenAPI file
5. Annotations

Example processing: +
 A vendor starts by fetching all available <<Configuration>>.  If
an `OASModelReader` was specified in that configuration list, its `buildModel`
method is called to form the starting OpenAPI model tree for this application. +
Any <<Vendor specific configuration>> are added on top of that starting model (overriding
conflicts), or create a new model if an `OASModelReader` was not registered. +
If an `OASFilter` was specified the vendor registers the filter with its framework,
which will call the filter upon any future internal model events (ie: adding new operation). +
Next, the vendor searches for a file as defined in the section <<Static OpenAPI files>>.
If found, it will read that document and merge with the model that it got from
the `OASModelReader`, where conflicting elements from the static file will override
the values from the original model. +
Lastly, if annotation scanning was not disabled,
the JAX-RS and OpenAPI annotations from the application will be processed, further
overriding any conflicting elements from the current model.



== Limitations

=== Internationalization
The 1.0 version of the MicroProfile OpenAPI spec does not require vendors to
support multiple languages based on the `Accept-Language`.  One reasonable
approach is for vendors to support unique keys (instead of hardcoded text) via
the various <<Documentation Mechanisms>>, so that the implementing framework can
perform a global replacement of the keys with the language-specific text that
matches the `Accept-Language` request for the `/openapi` endpoint.  A cache of
processed languages can be kept to improve performance. 
